config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static#index"

  resources :listings
  resources :categories

  get "/:page" => "static#show"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listings

  def name
    title
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :category
  belongs_to :user

  include PgSearch
  pg_search_scope :search_title, :against => [:title], :using => { :tsearch => {:prefix => true} }
  # multisearchable :against => [:title, :description]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings

  #paperclip
  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }, default_url: "public/images/thumb/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  include PgSearch
  pg_search_scope :search_title, :against => [:username]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ApplicationHelper

  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  after_filter :store_location

  def store_location
    # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categorys
  # GET /categorys.json
  def index
    @categories = Category.all
  end

  # GET /categorys/1
  # GET /categorys/1.json
  def show
  end

  # GET /categorys/new
  def new
    @category = Category.new
  end

  # GET /categorys/1/edit
  def edit
  end

  # POST /categorys
  # POST /categorys.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorys/1
  # PATCH/PUT /categorys/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorys/1
  # DELETE /categorys/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # before_filter :authorize_listing, only: [:edit]

  # def authorize_listing
  #   @listing = Listing.where(user_id: current_user.id)
  #   print 'rtftgfge'
  #   print @listing.inspect
  #
  #   if @listing.blank?
  #     flash[:error] = "You cannot access someone else's record."
  #     redirect_to root_path
  #   else
  #     redirect_to :controller => 'listings', :action => 'edit', :id => params[:id]
  #   end
  # end

  # GET /listings
  # GET /listings.json
  def index
    @categories = Category.all
    if params[:search].present?
      @listings = Listing.search_title(params[:search]).order("created_at DESC")
    else
      @listings = Listing.all.order("created_at DESC")
    end
  end

  def search
  end

  def search_results
    @listings = Listing.search_title(params[:search]).order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @categories = Category.all
  end

  # GET /listings/1/edit
  def edit
    @categories = Category.all

    @check = Listing.find(params[:id]).user_id
    if(@check != current_user.id)
      flash[:error] = "You cannot edit someone else's record."
      redirect_to listings_path
    end
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @categories = Category.all

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :category_id, :image)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    render "index.html"
  end

  def show
    render params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</p>
      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/edit.html.erb
<header>
  <h1>Edit Category</h1>
</header>

<%= render 'form' %>

app/views/categories/index.html.erb
<header>
  <h1>Categories</h1>

  <ul class="actions">
    <li><%= link_to 'New Category', new_category_path, class: "new" %></li>
  </ul>

</header>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<header>
  <h2><%= @category.title %></h2>

  <ul class="actions">
    <li><%= link_to fa_icon("list-alt") + ' Categories', category_path(@category), class: "btn btn-info" %></li>
    <li><%= link_to fa_icon("pencil") + ' Edit', edit_category_path(@category), class: "btn btn-primary" %></li>
    <li><%= link_to fa_icon("trash") + ' Delete', category_path(@category), method: :delete, data: { confirm: "Do you really want to delete this category?" }, class: "btn btn-danger" %></li>
  </ul>
</header>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Giarclist</title>
  <meta name="viewport" content="width-device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed_top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <%= link_to "Giarclist", root_path, class: "navbar-brand" %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'thinkful.png', class: 'logo' %>
        Thinklist
        <% end %> -->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="collapse">
        <ul class="nav navbar-nav">
          <!-- <li class="<%= "active" if current_page?("/")  %>"> -->
            <%#= link_to "Home", root_path %>
          <!-- </li> -->
          <li class="<%= "active" if current_page?("/listings")  %>">
            <%= link_to "Buy & Sell", listings_path %>
          </li>
          <!-- <li class="<%= "active" if current_page?("/categories")  %>"> -->
            <%#= link_to "Categories", categories_path %>
          <!-- </li> -->
          <li class="<%= "active" if current_page?("/help")  %>">
            <%= link_to "Help & Support", "/help" %>
          </li>
          <li class="<%= "active" if current_page?("/about")  %>">
            <%= link_to "About", "/about" %>
          </li>
        </ul>

        <% if !user_signed_in? %>
          <div class="navbar-right">
            <ul class="nav navbar-nav">
              <li class="<%= "active" if current_page?("/users/sign_in")  %>">
                <%= link_to "Sign In", new_user_session_path %>
              </li>
              <li class="<%= "active" if current_page?("/users/sign_up")  %>">
                <%= link_to "Sign Up", new_user_registration_path %>
              </li>
            </ul>
          </div>
        <% else %>
          <div class="navbar-right">
            <p class="navbar-text">
              Signed in as <%= current_user.email %>
            </p>
            <ul class="nav navbar-nav">
              <li class="<%= "active" if current_page?("/users/edit")  %>">
                <%= link_to "Manage Account", edit_user_registration_path %>
              </li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              </li>
              <% if current_user.avatar? %>
                <li class="round-image-50">
                  <%= image_tag(current_user.avatar.url(:thumb)) %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>



  <div id="main">

    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>

    <div><%= yield %></div>
  </div>

  <footer>
    <p>&copy; Giarclist Pte. Ltd. 2016</p>
  </footer>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</p>
      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.collection_select(:category_id, @categories, :id, :title)  %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :price, class: 'form-control', step: 'any', min: 0 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image %><br />
    <div><%= f.file_field :image %></div>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
<% end %>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/edit.html.erb
<header>
  <h1>Edit Listing</h1>
</header>

<%= render 'form' %>

app/views/listings/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<header>
  <h1>Listings</h1>

  <ul class="actions">
    <li><%= link_to 'New Listing', new_listing_path, class: "new" %></li>
  </ul>

</header>

<%= form_tag(listings_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Listings" %>
  <%= submit_tag "Search" %>
<% end %>

<% if @listings.present?  %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Category</th>
        <th>Price</th>
        <th>Seller</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @listings.each do |listing| %>
        <tr>
          <td><%= listing.title %></td>
          <td><%= listing.description %></td>
          <td><%= listing.category.title %></td>
          <td><%= number_to_currency(listing.price)  %></td>
          <td><%= listing.user.username %></td>
          <td><%= link_to 'Show', listing %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <br/>
  <p>There are no listings containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/listings/new.html.erb
<header>
  <h1>New Listing</h1>
</header>

<%= render 'form' %>

app/views/listings/show.html.erb
<header>
  <h2><%= @listing.title %></h2>

  <ul class="actions">
    <li><%= link_to fa_icon("list-alt") + ' Listings', listings_path, class: "btn btn-info" %></li>
    <% if user_signed_in? && (current_user.id == @listing.user_id) %>
      <li><%= link_to fa_icon("pencil") + ' Edit', edit_listing_path(@listing), class: "btn btn-primary" %></li>
      <li><%= link_to fa_icon("trash") + ' Delete', listing_path(@listing), method: :delete, data: { confirm: "Do you really want to delete this listing?" }, class: "btn btn-danger" %></li>
    <% end %>
  </ul>

</header>

<p>
  <strong>Category:</strong>
  <%= @listing.category.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@listing.price) %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @listing.user.username %>
  <% if @listing.user.avatar? %>
    <div class="round-image-50">
      <%= image_tag(@listing.user.avatar.url(:thumb)) %>
    </div>
  <% end %>
</p>

<div>
  <% if @listing.image? %>
    <strong>Image of Product or Service:</strong>
    <div><%= image_tag @listing.image.url(:medium) %></div>
  <% end %>
</div>